version: '3'
services:
    app:
        container_name: rapidApi
        restart: always
        build: .
        ports:
            - '5090:5090'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
